Repository ufal/neuralmonkey, pull requests merged in 2018-04, with the labels that each got.

#680 Debugger tensor runner
  neuralmonkey/learning_utils.py
  neuralmonkey/runners/__init__.py
  neuralmonkey/runners/representation_runner.py
  neuralmonkey/runners/tensor_runner.py
  tests/bahdanau.ini
Labels: discussion, work in progress

#675 Transformer import
  neuralmonkey/attention/scaled_dot_product.py
  neuralmonkey/decoders/autoregressive.py
  neuralmonkey/decoders/transformer.py
  neuralmonkey/encoders/transformer.py
  neuralmonkey/model/sequence.py
  neuralmonkey/readers/plain_text_reader.py
  neuralmonkey/tf_utils.py
  scripts/import_transformer.1.2.9.py
  scripts/import_transformer.1.3.2.py
Labels: feature

#697 Enable lists inside tuples
  neuralmonkey/config/parsing.py
Labels: bug

#698 BLEU evaluator can use multiple references
  neuralmonkey/evaluators/bleu.py
Labels: enhancement

#705 Fix warning in tensor runner
  neuralmonkey/runners/tensor_runner.py
Labels: bug

#702 Fix Transformer import
  scripts/import_transformer.1.2.9.py
  scripts/import_transformer.1.3.2.py
Labels: bug

#699 Optinal projection in stateful filler
  neuralmonkey/encoders/numpy_stateful_filler.py
Labels: enhancement
