Repository ufal/neuralmonkey, pull requests merged in 2019-03, with the labels that each got.

#806 Fix computation of perplexity
  neuralmonkey/evaluators/perplexity.py
Labels: bug

#793 Decoding loop refactor
  neuralmonkey/decoders/autoregressive.py
  neuralmonkey/trainers/rl_trainer.py
Labels: refactor

#808 Wrappers for reverting gradient during training
  neuralmonkey/model/gradient_reversal.py
  tests/classifier.ini
Labels: feature

#811 Fix blessing for Transformer decoder
  neuralmonkey/decoders/autoregressive.py
  tests/tests_run.sh
Labels: bug

#814 Allow to setting random seed in run script
  neuralmonkey/experiment.py
Labels: bug
